Failure # 1 (occurred at 2024-12-05_03-58-00)
[36mray::ImplicitFunc.train()[39m (pid=3348558, ip=141.142.254.119, actor_id=518a6e35a6c3a4d4570ea7a601000000, repr=train_tune_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/u/mbanisharifdehkordi/Github/Cell Counting/ray_tune.py", line 96, in train_tune_model
    cell_count, _ = model(inputs)
                    ^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CellCounter.forward() missing 1 required positional argument: 'cluster_input'
